# 3. IPYNB análisis dataset Pobreza

In [108]:
import pandas as pd

print(f'Pandas version: {pd.__version__}')

Pandas version: 3.0.0

### 3.1 — Exploración inicial

Muestra .head(10), .shape, .info() y .describe()

In [109]:
poverty = pd.read_csv('datasets/pip_dataset.csv')

display(poverty.head(10))
display(poverty.tail())
display(poverty.shape)
display(poverty.describe())

,country,year,reporting_level,welfare_type,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,...,decile8_thr,decile9_thr,gini,mld,polarization,palma_ratio,s80_s20_ratio,p90_p10_ratio,p90_p50_ratio,p50_p10_ratio
0,Albania,1996,national,consumption,2011,1996.0,0.0,0.920669,11.174149,44.618417,...,8.85,10.92,0.270103,0.119104,0.241293,0.928335,3.945872,3.568627,1.889273,1.888889
1,Albania,2002,national,consumption,2011,2002.0,1.0,1.570843,14.132118,49.669635,...,8.83,11.58,0.317390,0.164812,0.268982,1.215056,4.831625,3.979381,2.090253,1.903780
2,Albania,2005,national,consumption,2011,2005.0,1.0,0.860527,8.715685,38.545254,...,10.02,12.78,0.305957,0.154413,0.254529,1.142718,4.662236,3.872727,1.978328,1.957576
3,Albania,2008,national,consumption,2011,2008.0,1.0,0.313650,5.250542,31.110345,...,10.74,13.62,0.299847,0.148893,0.247311,1.114657,4.395911,3.574803,1.956897,1.826772
4,Albania,2012,national,consumption,2011,2012.0,1.0,0.849754,6.182414,34.528906,...,10.52,13.26,0.289605,0.138417,0.249988,1.041193,4.272573,3.632877,1.941435,1.871233
5,Albania,2014,national,consumption,2011,2014.0,2.0,1.580897,11.615621,37.033842,...,11.74,15.78,0.345989,0.198662,0.324310,1.376215,5.930924,5.173770,2.296943,2.252459
6,Albania,2015,national,consumption,2011,2015.0,2.0,0.245098,4.690767,24.461185,...,13.80,18.26,0.327537,0.175495,0.300364,1.248506,5.278241,4.599496,2.229548,2.062972
7,Albania,2016,national,consumption,2011,2016.0,2.0,0.410364,5.462612,23.903491,...,14.78,19.18,0.337363,0.187581,0.314380,1.306972,5.626880,4.930591,2.251174,2.190231
8,Albania,2016,national,income,2011,2016.0,4.0,6.681604,17.621649,39.949891,...,11.88,16.02,0.385656,0.273740,0.350360,1.696002,8.286575,6.965217,2.376855,2.930435
9,Albania,2017,national,consumption,2011,2017.0,2.0,0.428475,4.284743,23.828625,...,14.54,18.82,0.330557,0.179908,0.308522,1.259837,5.389502,4.635468,2.229858,2.078818

,country,year,reporting_level,welfare_type,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,...,decile8_thr,decile9_thr,gini,mld,polarization,palma_ratio,s80_s20_ratio,p90_p10_ratio,p90_p50_ratio,p50_p10_ratio
4872,Zambia,2010,national,consumption,2017,2010.0,4.0,68.456606,82.885088,93.044964,...,3.27,5.34,0.556215,0.539135,0.536149,4.278696,16.024650,10.470588,3.955556,2.647059
4873,Zambia,2015,national,consumption,2017,2015.0,4.0,61.352160,77.548045,90.747141,...,4.02,6.43,0.571361,0.604667,0.613181,4.995829,21.243915,13.978261,4.095541,3.413043
4874,Zimbabwe,2011,national,consumption,2017,2011.0,0.0,21.580063,47.857143,77.945113,...,7.25,10.54,0.431536,0.311153,0.388356,2.207938,8.526847,6.713376,2.773684,2.420382
4875,Zimbabwe,2017,national,consumption,2017,2017.0,0.0,34.206046,61.583570,84.109019,...,5.96,8.81,0.443371,0.322848,0.416694,2.307359,8.569542,6.574627,3.069686,2.141791
4876,Zimbabwe,2019,national,consumption,2017,2019.0,0.0,39.754533,64.509857,85.016315,...,5.76,9.01,0.502565,0.427862,0.463899,NaN,NaN,8.190909,3.400000,2.409091

(4877, 108)

,year,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,headcount_ratio_100,headcount_ratio_1000,headcount_ratio_2000,...,decile8_thr,decile9_thr,gini,mld,polarization,palma_ratio,s80_s20_ratio,p90_p10_ratio,p90_p50_ratio,p50_p10_ratio
count,4877.000000,4877.000000,4411.000000,4411.000000,4877.000000,4877.000000,4877.000000,4877.000000,4877.000000,4877.000000,...,4877.000000,4877.000000,4401.000000,4401.000000,4401.000000,4395.000000,4395.000000,4877.000000,4877.000000,4877.000000
mean,2005.759893,2013.999385,2005.939896,1.639084,11.081565,21.672687,36.538818,3.164721,50.351520,69.105964,...,26.273736,35.110607,0.375645,0.264371,0.327385,1.886528,8.219764,7.424451,2.532256,2.660335
std,9.438782,3.000308,9.497211,1.402898,18.190433,27.104145,33.674140,7.568626,36.002943,34.132391,...,24.171141,30.671393,0.088840,0.140325,0.101136,1.138502,6.018946,42.891943,0.954387,11.785204
min,1967.000000,2011.000000,1967.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.920154,...,1.010000,1.460000,0.177920,0.053563,0.146643,0.596408,2.430173,2.191176,1.475248,1.485294
25%,2000.000000,2011.000000,2000.000000,1.000000,0.278387,0.807877,3.032081,0.044772,10.328433,44.575897,...,8.680000,11.960000,0.308719,0.163090,0.252448,1.154071,4.720943,3.937500,2.017751,1.942113
50%,2007.000000,2011.000000,2007.000000,1.000000,2.041412,9.186717,28.582685,0.371755,55.337658,84.916259,...,16.980000,24.560000,0.355622,0.220968,0.300364,1.465800,6.171947,5.149826,2.290076,2.207904
75%,2013.000000,2017.000000,2014.000000,2.000000,13.390963,34.166712,64.864719,2.158480,85.133887,97.179433,...,35.550000,48.350000,0.427676,0.320859,0.380201,2.152142,9.043292,7.458333,2.780911,2.740385
max,2021.000000,2017.000000,2021.000000,6.000000,96.871427,99.999000,99.999000,79.532619,99.999000,100.000000,...,120.100000,164.700000,0.657556,0.937047,0.815704,8.343586,72.681737,2892.000000,11.491525,809.000000

Identifica cuántos países únicos hay en el dataset

In [110]:
unique_countries = poverty['country'].nunique()

print(f'Cantidad de países únicos: {unique_countries}')

Cantidad de países únicos: 177

Identifica el rango de años disponibles (valor mínimo y máximo de la columna de año)

In [111]:
max_year = poverty['year'].max()
min_year = poverty['year'].min()

print(f'Rango: {min_year} - {max_year}')
print(f'Diferencia: {max_year - min_year} años')

Rango: 1967 - 2021
Diferencia: 54 años

### 3.2 — Limpieza y filtrado

Elimina las filas donde el indicador principal de pobreza (porcentaje de población bajo la línea de pobreza) sea nulo

In [112]:
poverty = poverty.dropna(subset=['headcount_ratio_international_povline'])

Filtra los datos y crea un DataFrame df_reciente que contenga únicamente los registros del año más reciente disponible

In [113]:
df_reciente = poverty[poverty['year'] == max_year]

df_reciente.head()

,country,year,reporting_level,welfare_type,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,...,decile8_thr,decile9_thr,gini,mld,polarization,palma_ratio,s80_s20_ratio,p90_p10_ratio,p90_p50_ratio,p50_p10_ratio
1108,Indonesia,2021,national,consumption,2011,2021.0,5.0,2.163278,17.967401,50.220043,...,9.52,13.10,0.373426,0.228364,0.322504,1.626294,6.287901,5.000000,2.390511,2.091603
1109,Indonesia,2021,rural,consumption,2011,2021.0,5.0,1.975943,19.123040,54.512639,...,8.36,10.58,0.315339,0.162352,0.278900,1.190194,4.836385,4.116732,2.062378,1.996109
1110,Indonesia,2021,urban,consumption,2011,2021.0,5.0,2.302937,17.105866,47.019890,...,10.70,15.30,0.400631,0.263616,0.358487,1.860306,7.229679,5.730337,2.642487,2.168539
3546,Indonesia,2021,national,consumption,2017,2021.0,5.0,3.547444,22.393805,60.637832,...,10.06,13.94,0.379157,0.235409,0.326286,1.676786,6.446514,5.069091,2.428571,2.087273
3547,Indonesia,2021,rural,consumption,2017,2021.0,5.0,4.623175,27.027257,69.035615,...,8.31,10.54,0.315339,0.162352,0.278900,1.190194,4.836385,4.117188,2.062622,1.996094

Crea un DataFrame df_extrema con los países donde la tasa de pobreza extrema supere el 30%

In [114]:
df_extrema = poverty[poverty['headcount_ratio_international_povline'] > 30]

df_extrema.head()

,country,year,reporting_level,welfare_type,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,...,decile8_thr,decile9_thr,gini,mld,polarization,palma_ratio,s80_s20_ratio,p90_p10_ratio,p90_p50_ratio,p50_p10_ratio
17,Angola,2000,national,consumption,2011,2000.21,0.0,36.374478,59.678611,80.548714,...,5.36,8.06,0.519569,0.512576,0.464340,3.653264,17.654010,12.212121,3.100000,3.939394
18,Angola,2008,national,consumption,2011,2008.50,1.0,34.446857,60.604568,82.921126,...,5.07,6.98,0.427155,0.311632,0.391365,2.147126,8.942374,6.843137,2.674330,2.558824
19,Angola,2018,national,consumption,2011,2018.17,2.0,49.902954,71.484826,88.481178,...,4.07,5.97,0.512721,0.477890,0.470982,3.465666,14.786824,9.950000,3.142105,3.166667
114,Bangladesh,1983,national,consumption,2011,1983.50,0.0,38.804918,83.218282,97.115527,...,3.03,3.76,0.258765,0.112144,0.203966,0.910779,3.688356,3.081967,1.757009,1.754098
115,Bangladesh,1985,national,consumption,2011,1985.50,0.0,34.182852,78.515313,95.643795,...,3.28,4.15,0.269175,0.120314,0.209518,0.980953,3.709653,3.051471,1.828194,1.669118

Ordena df_extrema de mayor a menor tasa de pobreza y muestra los 10 primeros países

In [115]:
df_extrema.sort_values(by='headcount_ratio_international_povline', ascending=False).head(10)

,country,year,reporting_level,welfare_type,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,...,decile8_thr,decile9_thr,gini,mld,polarization,palma_ratio,s80_s20_ratio,p90_p10_ratio,p90_p50_ratio,p50_p10_ratio
2770,China,1981,rural,income,2017,1981.00,0.0,96.871427,99.999000,99.999000,...,1.29,1.58,0.247292,0.101958,0.202851,0.843064,3.542433,3.098039,1.736264,1.784314
332,China,1981,rural,income,2011,1981.00,0.0,95.372817,99.918437,99.999000,...,1.25,1.54,0.247292,0.101958,0.202851,0.843064,3.542433,3.142857,1.730337,1.816327
521,Democratic Republic of Congo,2004,national,consumption,2011,2004.89,0.0,94.278983,98.518720,99.731587,...,1.01,1.46,0.421636,0.300818,0.383858,2.079527,8.523032,6.636364,2.754717,2.409091
865,Guinea,1991,national,consumption,2011,1991.00,0.0,91.836413,98.546042,99.999000,...,1.20,1.74,0.468430,0.450983,0.490528,2.800359,16.520963,14.500000,3.107143,4.666667
2769,China,1981,national,income,2017,1981.00,0.0,91.623242,99.669404,99.983685,...,1.62,2.05,0.281641,0.128363,0.252109,0.974049,4.203515,3.796296,2.009804,1.888889
2959,Democratic Republic of Congo,2004,national,consumption,2017,2004.89,0.0,91.467302,97.567663,99.702615,...,1.37,1.98,0.421636,0.300818,0.383858,2.079527,8.523032,6.600000,2.788732,2.366667
2773,China,1984,rural,income,2017,1984.00,0.0,88.666354,98.020074,99.999000,...,1.79,2.24,0.266861,0.118113,0.216226,0.943520,3.846125,3.343284,1.821138,1.835821
331,China,1981,national,income,2011,1981.00,0.0,88.091114,99.315321,99.964043,...,1.58,2.00,0.281641,0.128363,0.252109,0.974049,4.203515,3.846154,2.000000,1.923077
3303,Guinea,1991,national,consumption,2017,1991.00,0.0,87.870383,96.904827,99.999000,...,1.63,2.36,0.468430,0.450983,0.490528,2.800359,16.520963,14.750000,3.105263,4.750000
2169,Tanzania,2000,national,consumption,2011,2000.33,1.0,86.230084,96.306067,99.405298,...,1.59,2.20,0.373011,0.231628,0.328084,1.601401,6.590794,5.365854,2.471910,2.170732

### 3.3 — Agrupación por región

Agrupa los datos por región geográfica y calcula: 
- La tasa de pobreza promedio por región
- El coeficiente de Gini promedio por región (si está disponible)
- El número de países por región

In [116]:
# Agrupar los datos
regiones = {
    'Africa': [
        'Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso',
        'Burundi', 'Cameroon', 'Cape Verde', 'Central African Republic',
        'Chad', 'Comoros', 'Congo', 'Democratic Republic of Congo',
        'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eswatini', 'Ethiopia',
        'Gabon', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau',
        'Ivory Coast', 'Kenya', 'Lesotho', 'Liberia', 'Libya',
        'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius',
        'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria',
        'Rwanda', 'Sao Tome and Principe', 'Senegal', 'Seychelles',
        'Sierra Leone', 'Somalia', 'South Africa', 'South Sudan',
        'Sudan', 'Tanzania', 'Togo', 'Tunisia', 'Uganda',
        'Zambia', 'Zimbabwe'
    ],

    'Asia': [
        'Armenia', 'Azerbaijan', 'Bangladesh', 'Bhutan',
        'Cambodia', 'China', 'Georgia', 'India', 'Indonesia',
        'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan',
        'Kazakhstan', 'Kyrgyz Republic', 'Laos', 'Lebanon',
        'Malaysia', 'Mongolia', 'Myanmar', 'Nepal',
        'Pakistan', 'Philippines', 'Sri Lanka', 'Syria',
        'Tajikistan', 'Thailand', 'Timor-Leste', 'Turkey',
        'Turkmenistan', 'Uzbekistan', 'Vietnam', 'Yemen'
    ],

    'Europe': [
        'Albania', 'Austria', 'Belarus', 'Belgium',
        'Bosnia and Herzegovina', 'Bulgaria', 'Croatia',
        'Czech Republic', 'Denmark', 'Estonia', 'Finland',
        'France', 'Germany', 'Greece', 'Hungary',
        'Iceland', 'Ireland', 'Italy', 'Kosovo',
        'Latvia', 'Lithuania', 'Luxembourg', 'Moldova',
        'Montenegro', 'Netherlands', 'North Macedonia',
        'Norway', 'Poland', 'Portugal', 'Romania',
        'Russia', 'Serbia', 'Slovakia', 'Slovenia',
        'Spain', 'Sweden', 'Switzerland', 'Ukraine',
        'United Kingdom'
    ],

    'North America': [
        'Belize', 'Canada', 'Costa Rica', 'Cuba',
        'Dominican Republic', 'El Salvador', 'Guatemala',
        'Haiti', 'Honduras', 'Jamaica', 'Mexico',
        'Nicaragua', 'Panama', 'United States'
    ],

    'South America': [
        'Argentina', 'Bolivia', 'Brazil', 'Chile',
        'Colombia', 'Ecuador', 'Guyana', 'Paraguay',
        'Peru', 'Suriname', 'Uruguay', 'Venezuela'
    ],

    'Oceania': [
        'Australia', 'Fiji', 'New Zealand',
        'Papua New Guinea', 'Samoa'
    ],

    'Other': ['World']
}

country_region = {}

for region, countries in regiones.items():
    for country in countries:
        country_region[country] = region

poverty['region'] = poverty['country'].map(country_region)

poverty.head()

C:\Users\User\AppData\Local\Temp\ipykernel_7908\2657704475.py:70: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  poverty['region'] = poverty['country'].map(country_region)

,country,year,reporting_level,welfare_type,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,...,decile9_thr,gini,mld,polarization,palma_ratio,s80_s20_ratio,p90_p10_ratio,p90_p50_ratio,p50_p10_ratio,region
0,Albania,1996,national,consumption,2011,1996.0,0.0,0.920669,11.174149,44.618417,...,10.92,0.270103,0.119104,0.241293,0.928335,3.945872,3.568627,1.889273,1.888889,Europe
1,Albania,2002,national,consumption,2011,2002.0,1.0,1.570843,14.132118,49.669635,...,11.58,0.317390,0.164812,0.268982,1.215056,4.831625,3.979381,2.090253,1.903780,Europe
2,Albania,2005,national,consumption,2011,2005.0,1.0,0.860527,8.715685,38.545254,...,12.78,0.305957,0.154413,0.254529,1.142718,4.662236,3.872727,1.978328,1.957576,Europe
3,Albania,2008,national,consumption,2011,2008.0,1.0,0.313650,5.250542,31.110345,...,13.62,0.299847,0.148893,0.247311,1.114657,4.395911,3.574803,1.956897,1.826772,Europe
4,Albania,2012,national,consumption,2011,2012.0,1.0,0.849754,6.182414,34.528906,...,13.26,0.289605,0.138417,0.249988,1.041193,4.272573,3.632877,1.941435,1.871233,Europe

In [117]:
# se realizan las 3 operaciones usando .agg()
pov_reg = poverty.groupby('region').agg({
    'headcount_ratio_international_povline': 'mean',
    'gini':'mean',
    'country': 'nunique'
})

display(pov_reg)

               headcount_ratio_international_povline      gini  country
region
Africa                                     41.106749  0.431383       50
Asia                                       15.782373  0.358774       31
Europe                                      1.014168  0.314999       38
North America                               9.128220  0.474343       13
Oceania                                     5.146332  0.360525        4
Other                                      22.431379       NaN        1
South America                               7.909350  0.497281       12

Muestra la región con la mayor y la menor tasa de pobreza promedio

In [118]:
reg_tasa_min = pov_reg['headcount_ratio_international_povline'].idxmin()
reg_tasa_max = pov_reg['headcount_ratio_international_povline'].idxmax()

print(f'Región con menor tasa de pobreza promedio: {reg_tasa_min}')
print(f'Región con mayor tasa de pobreza promedio: {reg_tasa_max}')

Región con menor tasa de pobreza promedio: Europe
Región con mayor tasa de pobreza promedio: Africa

### 3.4 — Análisis y preguntas

**P1. ¿Cuáles son los 5 países con mayor tasa de pobreza en el año más reciente disponible?**

In [119]:
df_reciente.sort_values(by='headcount_ratio_international_povline', ascending=False).head(5)

,country,year,reporting_level,welfare_type,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,...,decile8_thr,decile9_thr,gini,mld,polarization,palma_ratio,s80_s20_ratio,p90_p10_ratio,p90_p50_ratio,p50_p10_ratio
3547,Indonesia,2021,rural,consumption,2017,2021.0,5.0,4.623175,27.027257,69.035615,...,8.31,10.54,0.315339,0.162352,0.278900,1.190194,4.836385,4.117188,2.062622,1.996094
3546,Indonesia,2021,national,consumption,2017,2021.0,5.0,3.547444,22.393805,60.637832,...,10.06,13.94,0.379157,0.235409,0.326286,1.676786,6.446514,5.069091,2.428571,2.087273
3548,Indonesia,2021,urban,consumption,2017,2021.0,5.0,2.745481,18.939541,54.377240,...,11.72,16.76,0.400631,0.263616,0.358487,1.860306,7.229679,5.739726,2.643533,2.171233
1110,Indonesia,2021,urban,consumption,2011,2021.0,5.0,2.302937,17.105866,47.019890,...,10.70,15.30,0.400631,0.263616,0.358487,1.860306,7.229679,5.730337,2.642487,2.168539
1108,Indonesia,2021,national,consumption,2011,2021.0,5.0,2.163278,17.967401,50.220043,...,9.52,13.10,0.373426,0.228364,0.322504,1.626294,6.287901,5.000000,2.390511,2.091603

*Los resultados muestran que existen problemas económicos fuertes y desigualdad en Indonesia*

**P2. ¿Cuáles son los 5 países con menor tasa de pobreza en ese mismo año?**

In [123]:
df_reciente.sort_values(by='headcount_ratio_international_povline', ascending=True).head(5)

,country,year,reporting_level,welfare_type,ppp_version,survey_year,survey_comparability,headcount_ratio_international_povline,headcount_ratio_lower_mid_income_povline,headcount_ratio_upper_mid_income_povline,...,decile8_thr,decile9_thr,gini,mld,polarization,palma_ratio,s80_s20_ratio,p90_p10_ratio,p90_p50_ratio,p50_p10_ratio
1109,Indonesia,2021,rural,consumption,2011,2021.0,5.0,1.975943,19.123040,54.512639,...,8.36,10.58,0.315339,0.162352,0.278900,1.190194,4.836385,4.116732,2.062378,1.996109
1108,Indonesia,2021,national,consumption,2011,2021.0,5.0,2.163278,17.967401,50.220043,...,9.52,13.10,0.373426,0.228364,0.322504,1.626294,6.287901,5.000000,2.390511,2.091603
1110,Indonesia,2021,urban,consumption,2011,2021.0,5.0,2.302937,17.105866,47.019890,...,10.70,15.30,0.400631,0.263616,0.358487,1.860306,7.229679,5.730337,2.642487,2.168539
3548,Indonesia,2021,urban,consumption,2017,2021.0,5.0,2.745481,18.939541,54.377240,...,11.72,16.76,0.400631,0.263616,0.358487,1.860306,7.229679,5.739726,2.643533,2.171233
3546,Indonesia,2021,national,consumption,2017,2021.0,5.0,3.547444,22.393805,60.637832,...,10.06,13.94,0.379157,0.235409,0.326286,1.676786,6.446514,5.069091,2.428571,2.087273

*Los registros en 2021 solo tienen como país a Indonesia, por lo que los resultados son contradictorios*

**P3. Usando .corr(), ¿existe relación entre el coeficiente de Gini (desigualdad) y la tasa de pobreza? ¿Qué nos dice esto?**

![correlacion](correlacion.png)

In [121]:
correlacion = df_reciente['gini'].corr(df_reciente['headcount_ratio_international_povline'])

print(f'Correlación: {correlacion:.2f}')

Correlación: -0.32

*La correlación fue de -0.32, lo que muestra una relación débil (negativa) entre la desigualdad y la pobreza*

**P4. ¿Ha aumentado o disminuido la tasa de pobreza promedio mundial a lo largo de los años disponibles? Agrupa por año y calcula el promedio para responder**

In [122]:
pobreza_anual = poverty.groupby('year')['headcount_ratio_international_povline'].mean().reset_index()

pobreza_anual.head()

   year  headcount_ratio_international_povline
0  1967                               7.869248
1  1969                               0.234306
2  1971                               2.249591
3  1974                               0.426141
4  1975                               0.748501

*Se evidencia cómo ha cambiado la situación mundial con el tiempo, la tendencia muestra si la pobreza ha aumentado o disminuido a lo largo de los años*